apiVersion: v1
kind: Service
metadata:
  name: ebpf-tracer-metrics
  namespace: ebpf-tracer
  labels:
    app.kubernetes.io/name: ebpf-tracer
    app.kubernetes.io/component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  selector:
    app.kubernetes.io/name: ebpf-tracer
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ebpf-tracer-api
  namespace: ebpf-tracer
  labels:
    app.kubernetes.io/name: ebpf-tracer
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ebpf-tracer
  ports:
  - name: api
    port: 80
    targetPort: 8080
    protocol: TCP

---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ebpf-tracer
  namespace: ebpf-tracer
  labels:
    app.kubernetes.io/name: ebpf-tracer
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ebpf-tracer
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace

---
# NetworkPolicy to secure the tracer
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ebpf-tracer-netpol
  namespace: ebpf-tracer
  labels:
    app.kubernetes.io/name: ebpf-tracer
    app.kubernetes.io/component: security
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ebpf-tracer
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9090
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 14268  # Jaeger collector
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 443   # Kubernetes API
